-- MySQL Script generated by MySQL Workbench
-- 09/21/17 10:59:37
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_formsus_t
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_formsus_t` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_formsus_t` ;

-- -----------------------------------------------------
-- Table `db_formsus_t`.`estabelecimento_de_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`estabelecimento_de_saude` (
  `id_estabelecimento_de_saude` INT(11) NOT NULL AUTO_INCREMENT,
  `cnes` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id_estabelecimento_de_saude` ASC),
  UNIQUE INDEX `cnes_UNIQUE` (`cnes` ASC),
  PRIMARY KEY (`id_estabelecimento_de_saude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`paciente` (
  `id_paciente` INT(11) NOT NULL,
  `num_prontuario` VARCHAR(22) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `sexo` VARCHAR(2) NOT NULL COMMENT 'F para feminino e M para masculino',
  `cns` INT(22) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cor` VARCHAR(2) NOT NULL,
  `etnia` VARCHAR(2) NOT NULL,
  `nome_mae` VARCHAR(150) NOT NULL,
  `telefone_mae` VARCHAR(26) NOT NULL,
  `nome_responsavel` VARCHAR(150) NOT NULL,
  `telefone_responsavel` VARCHAR(26) NOT NULL,
  `peso` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `logradouro` VARCHAR(150) NOT NULL,
  `num_residencia` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(150) NOT NULL,
  `municipio` VARCHAR(150) NOT NULL,
  `cod_ibge_municipio` VARCHAR(22) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`id_paciente`),
  UNIQUE INDEX `numProntuario_UNIQUE` (`num_prontuario` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id_paciente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`solicitante` (
  `id_solicitante` INT(11) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `tipo_doc` BINARY NOT NULL COMMENT '0 para CNS e 1 para CPF',
  `num_doc` VARCHAR(16) NULL,
  PRIMARY KEY (`id_solicitante`),
  UNIQUE INDEX `id_UNIQUE` (`id_solicitante` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`cid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`cid` (
  `id_cid` INT NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(6) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_cid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`proc_justificativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`proc_justificativa` (
  `id_proc_justificativa` INT NOT NULL AUTO_INCREMENT,
  `observacoes` TEXT NULL,
  `cid_id_principal` INT NOT NULL,
  `cid_id_secundario` INT NULL,
  `cid_id_causas_assoc` INT NULL,
  PRIMARY KEY (`id_proc_justificativa`),
  UNIQUE INDEX `id_UNIQUE` (`id_proc_justificativa` ASC),
  INDEX `fk_proc_justificativa_cid1_idx` (`cid_id_principal` ASC),
  INDEX `fk_proc_justificativa_cid2_idx` (`cid_id_secundario` ASC),
  INDEX `fk_proc_justificativa_cid3_idx` (`cid_id_causas_assoc` ASC),
  CONSTRAINT `fk_proc_justificativa_cid1`
    FOREIGN KEY (`cid_id_principal`)
    REFERENCES `db_formsus_t`.`cid` (`id_cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proc_justificativa_cid2`
    FOREIGN KEY (`cid_id_secundario`)
    REFERENCES `db_formsus_t`.`cid` (`id_cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proc_justificativa_cid3`
    FOREIGN KEY (`cid_id_causas_assoc`)
    REFERENCES `db_formsus_t`.`cid` (`id_cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`autorizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`autorizacao` (
  `id_autorizacao` INT NOT NULL AUTO_INCREMENT,
  `autorizador` VARCHAR(150) NULL,
  `cod_org_emissor` VARCHAR(10) NULL,
  `tipo_doc` BINARY NULL COMMENT '0 para CNS e 1 para CPF',
  `num_doc` VARCHAR(16) NULL,
  `data` DATE NOT NULL,
  `num_autorizacao` VARCHAR(20) NOT NULL,
  `data_val_ini` DATE NULL,
  `data_val_fim` DATE NULL,
  PRIMARY KEY (`id_autorizacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`formulario` (
  `id_formulario` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `autenticacao` VARCHAR(300) NOT NULL,
  `paciente_id` INT(11) NOT NULL,
  `solicitante_id` INT(11) NOT NULL,
  `estabelecimento_de_saude_id_solicitante` INT(11) NOT NULL,
  `estabelecimento_de_saude_id_executante` INT(11) NULL,
  `proc_justificativa_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  `autorizacao_id` INT NULL,
  PRIMARY KEY (`id_formulario`),
  UNIQUE INDEX `id_UNIQUE` (`id_formulario` ASC),
  INDEX `fk_formulario_paciente1_idx` (`paciente_id` ASC),
  INDEX `fk_formulario_solicitante1_idx` (`solicitante_id` ASC),
  INDEX `fk_formulario_estabelecimento_de_saude1_idx` (`estabelecimento_de_saude_id_solicitante` ASC),
  INDEX `fk_formulario_estabelecimento_de_saude2_idx` (`estabelecimento_de_saude_id_executante` ASC),
  INDEX `fk_formulario_proc_justificativa1_idx` (`proc_justificativa_id` ASC),
  INDEX `fk_formulario_status1_idx` (`status_id` ASC),
  INDEX `fk_formulario_autorizacao1_idx` (`autorizacao_id` ASC),
  CONSTRAINT `fk_formulario_paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `db_formsus_t`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_solicitante1`
    FOREIGN KEY (`solicitante_id`)
    REFERENCES `db_formsus_t`.`solicitante` (`id_solicitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_estabelecimento_de_saude1`
    FOREIGN KEY (`estabelecimento_de_saude_id_solicitante`)
    REFERENCES `db_formsus_t`.`estabelecimento_de_saude` (`id_estabelecimento_de_saude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_estabelecimento_de_saude2`
    FOREIGN KEY (`estabelecimento_de_saude_id_executante`)
    REFERENCES `db_formsus_t`.`estabelecimento_de_saude` (`id_estabelecimento_de_saude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_proc_justificativa1`
    FOREIGN KEY (`proc_justificativa_id`)
    REFERENCES `db_formsus_t`.`proc_justificativa` (`id_proc_justificativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `db_formsus_t`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_autorizacao1`
    FOREIGN KEY (`autorizacao_id`)
    REFERENCES `db_formsus_t`.`autorizacao` (`id_autorizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`procedimento_sus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`procedimento_sus` (
  `id_procedimento_sus` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(300) NOT NULL,
  `nome_abrev` VARCHAR(200) NULL,
  PRIMARY KEY (`id_procedimento_sus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `login` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `setor` VARCHAR(100) NOT NULL,
  `perfil` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`auditoria` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `procedimento_realizado` VARCHAR(200) NOT NULL,
  `usuario_id` INT NOT NULL,
  `formulario_id` INT NULL,
  PRIMARY KEY (`id_auditoria`),
  INDEX `fk_auditoria_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_auditoria_formulario1_idx` (`formulario_id` ASC),
  CONSTRAINT `fk_auditoria_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_formsus_t`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auditoria_formulario1`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `db_formsus_t`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`formulario_has_procedimento_sus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`formulario_has_procedimento_sus` (
  `formulario_id` INT NOT NULL,
  `procedimento_sus_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`formulario_id`, `procedimento_sus_id`),
  INDEX `fk_formulario_has_procedimento_sus_procedimento_sus1_idx` (`procedimento_sus_id` ASC),
  INDEX `fk_formulario_has_procedimento_sus_formulario1_idx` (`formulario_id` ASC),
  CONSTRAINT `fk_formulario_has_procedimento_sus_formulario1`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `db_formsus_t`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_has_procedimento_sus_procedimento_sus1`
    FOREIGN KEY (`procedimento_sus_id`)
    REFERENCES `db_formsus_t`.`procedimento_sus` (`id_procedimento_sus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_formsus_t`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_formsus_t`.`config` (
  `id_config` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(150) NULL,
  `paranmetro` VARCHAR(50) NULL,
  PRIMARY KEY (`id_config`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
